[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml"
]

[window]
opacity = 0.8
blur = true

[font]
size = 11.0

[font.normal]
family = "Adwaita Mono"
style = "Regular"

[font.bold]
family = "Adwaita Mono"
style = "Bold"

[font.italic]
family = "Adwaita Mono"
style = "Italic"

[font.bold_italic]
family = "Adwaita Mono"
style = "Bold Italic"
