include themes/noctalia.conf


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
hide_window_decorations yes
background_blur 1
dynamic_background_opacity yes
background_opacity 0.90
font_family Adwaita Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11
# END_KITTY_THEME
