[colors.primary]
background = '#15130e'
foreground = '#e8e2d8'

[colors.cursor]
text = '#15130e'
cursor = '#e8e2d8'

[colors.vi_mode_cursor]
text = '#15130e'
cursor = '#dbc675'

[colors.search.matches]
foreground = '#4b4739'
background = '#b2d090'

[colors.search.focused_match]
foreground = '#4b4739'
background = '#dbc675'

[colors.footer_bar]
foreground = '#4b4739'
background = '#e8e2d8'

[colors.hints.start]
foreground = '#4b4739'
background = '#d2c69f'

[colors.hints.end]
foreground = '#4b4739'
background = '#d2c69f'

[colors.selection]
text = '#cdc6b4'
background = '#4b4739'


[colors.normal]
black   = '#4b4739'
red     = '#ffb4ab'
green   = '#dbc675'
yellow  = '#d2c69f'
blue    = '#b2d090'
magenta = '#dbc675'
cyan    = '#d2c69f'
white   = '#e8e2d8'


[colors.bright]
black   = '#979080'
red     = '#ffb4ab'
green   = '#dbc675'
yellow  = '#d2c69f'
blue    = '#b2d090'
magenta = '#dbc675'
cyan    = '#d2c69f'
white   = '#e8e2d8'


[colors.dim]
black   = '#4b4739'
red     = '#ffb4ab'
green   = '#dbc675'
yellow  = '#d2c69f'
blue    = '#b2d090'
magenta = '#dbc675'
cyan    = '#d2c69f'
white   = '#e8e2d8'
