[colors.primary]
background = '#121318'
foreground = '#e3e1e8'

[colors.cursor]
text = '#121318'
cursor = '#e3e1e8'

[colors.vi_mode_cursor]
text = '#121318'
cursor = '#bcc8ff'

[colors.search.matches]
foreground = '#454651'
background = '#fdb2f5'

[colors.search.focused_match]
foreground = '#454651'
background = '#bcc8ff'

[colors.footer_bar]
foreground = '#454651'
background = '#e3e1e8'

[colors.hints.start]
foreground = '#454651'
background = '#bfc5e7'

[colors.hints.end]
foreground = '#454651'
background = '#bfc5e7'

[colors.selection]
text = '#c5c5d2'
background = '#454651'


[colors.normal]
black   = '#454651'
red     = '#ffb4ab'
green   = '#bcc8ff'
yellow  = '#bfc5e7'
blue    = '#fdb2f5'
magenta = '#b7c4ff'
cyan    = '#bfc5e7'
white   = '#e3e1e8'


[colors.bright]
black   = '#8f909c'
red     = '#ffb4ab'
green   = '#bcc8ff'
yellow  = '#bfc5e7'
blue    = '#fdb2f5'
magenta = '#b7c4ff'
cyan    = '#bfc5e7'
white   = '#e3e1e8'


[colors.dim]
black   = '#454651'
red     = '#ffb4ab'
green   = '#bcc8ff'
yellow  = '#bfc5e7'
blue    = '#fdb2f5'
magenta = '#b7c4ff'
cyan    = '#bfc5e7'
white   = '#e3e1e8'
